### ISSUE TITLE
how to remove background lines?

### ISSUE THREAD

**Issue by a00101** [cpwardell/barplot3d#1]
Thanks for developing.

Help to remove background lines.
Thanks.

**Comment by cpwardell** [comment]
It's in the documentation and vignette; you must set the "gridlines" argument to "FALSE".  In the example below, I have also removed the vertical Z axis by setting "zlabels" to "FALSE".

barplot3d(rows=2, cols=2, z=1:4, gridlines = FALSE, zlabels = FALSE)

It's important to close your current RGL window, otherwise you will continue plotting in the same window and it will look like nothing has changed.

Good luck
Chris
